# Generated by Django 2.1.1 on 2018-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreC', models.CharField(max_length=50)),
                ('TituloAcademico', models.CharField(max_length=50)),
            ],
        ),
    ]
