# Generated by Django 2.1.1 on 2018-09-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_catedratico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catedratico',
            old_name='NombreC',
            new_name='NombreCatedratico',
        ),
    ]
